### ISSUE TITLE
Form field types don't get inferred from zod schema

### ISSUE THREAD

**Issue by pavle99** [TanStack/form#1066]
### Describe the bug

Without type casting the default values, the form type gets inferred as `ReactFormExtendedApi<TYPE, Validator<unknown, z.ZodType<any, z.ZodTypeDef, any>>>` where `TYPE` is the type of object passed to default values instead of it being the type inferred from the zod schema.

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-form-9w9uhn8b?file=src%2Findex.tsx

### Steps to reproduce

Try removing the `as User` in line 35 in `index.tsx` file and see how the type of the form changes when you add/remove/modify any of the fields in the default values.

### Expected behavior

Expected the form type to be inferred from the zod schema passed, as well as have type safety in default values without needing to manually cast the type.

### How often does this bug happen?

Every time

### Platform

OS: Windows 11
Browser: Chrome
Version: 130.0.6723.71 (Official Build) (64-bit)

### TanStack Form adapter

react-form

### TanStack Form version

0.40.0

### TypeScript version

5.6.3

**Comment by crutchcorn** [comment]
The `as User` cast is the correct way to do this. Our TS inferencing is already complex enough that we can't handle inferring from _both_ `defaultValues` and `validators.onChange` et al
