### ISSUE TITLE
Balastrong Tutorial results in 404

### ISSUE THREAD

**Issue by TheGreyfeather** [TanStack/form#1072]
### Describe the bug

When attempting to navigate to [https://tanstack.com/form/latest/docs/framework/react/community/balastrong-tutorial](https://tanstack.com/form/latest/docs/framework/react/community/balastrong-tutorial), the page returns a 404 HTTP error

### Your minimal, reproducible example

https://tanstack.com/form/latest/docs/framework/react/community/balastrong-tutorial

### Steps to reproduce

Navigate to Tanstack Forms documentation.
Select react as the framework, version latest.
Attempt to navigate to Balastrong Tutorial.
Receive 404 page if navigating on current page.
If you open in a blank tab, then there's a more detailed error.

### Expected behavior

I expected to see the documentation associated with Balastrong's tutorial as written here:
https://github.com/TanStack/form/blob/main/docs/framework/react/community/balastrongs-tutorial.md

While the documentation is links to specific YouTube videos with timestamps, it does seem helpful to have easier access to this resource while browsing the documentation

### How often does this bug happen?

Every time

### Platform

OS: Windows 10 

Browser: Chrome 
Version: 131
Browser: Firefox
Version: 133

### TanStack Form adapter

None

### TanStack Form version

v0.40.1

### Additional context

The page is however, accessible at https://tanstack.com/form/latest/docs/framework/react/community/balastrongs-tutorial

**Comment by Balastrong** [comment]
Typo in the filename, fixed now. Thanks!
