### ISSUE TITLE
Validation onBlur ?

### ISSUE THREAD

**Issue by theodorDiaconu** [TanStack/form#305]
Can we fine-tune when to do the validation ? It would be nice to provide a way to debounce it to a configurable amount or on certain events (keyUp, onSubmit)

**Comment by theodorDiaconu** [comment]
I can see this: validateOnSubmit, but can't this be configurable at field level ?

Also it would be very good to provide recipes with some easy validation tools, (not integrate it here, just sample like) 

```validate={{minLength: 10}}```

**Comment by joepuzzo** [comment]
I will see if i can add validateOnSubmit to field level. Will get back to ya by end of day.

**Comment by joepuzzo** [comment]
This is in latest version!

**Comment by theodorDiaconu** [comment]
Woop woop. Very nice I definitely made the right choice sticking to this framework. Look here to provide examples https://github.com/jquense/yup (propper schema validation) also please take a look at: https://github.com/jaredpalmer/formik for inspiration

I think we need 4 types of validation hooks to have this complete this:
onKeyUp
onBlur
onSubmit
debounced

**Comment by joepuzzo** [comment]
so i dont want to include a validation lib as part of this lib.. want to keep it simple and generic.

**Comment by joepuzzo** [comment]
That is the beauty of the lib is that you can choose to use somthing like Yup or whatever you want

**Comment by theodorDiaconu** [comment]
Indeed I just mentioned to provide some recipes for newbies to get around the concept, not add a new dependency. Cheers

**Comment by joepuzzo** [comment]
So can we close this issue? Was this simply for the field level validateOnSubmit?
