### ISSUE TITLE
Reference to FieldScope in form

### ISSUE THREAD

**Issue by paulbalomiri** [TanStack/form#359]
Hi,
I have a Use-Case where i'm using a `react-table` contained in a `react-form` with row-level and form-level submit actions.
The `form_context.value` can contain either the entire form or just the values within it's `FieldContext`. 

Adding a `value_path` would help to distinguish between the case where it contains all of the form's values or just a specific part of them (a row in this case).

https://github.com/tannerlinsley/react-form/blob/498692038ba173dea975f6e1e64cf66fc7ef5d9d/src/hooks/useFieldScope.js#L16

Do you think that it would be a good idea to add a `value-path` prop here?
**EDIT:** also, perhaps the useField("contextualized_name") should return a `parent_scope_path` pointing to the path of the parent `FieldScope` 

P.S. I'm writing in coffeescript, so sorry for all the snake_casing

**Comment by crutchcorn** [comment]
Hey all, I'm closing this issue as it appears to be related to a version of the **old** non-current `@tanstack/react-form` and friend APIs. We're looking to 1.x soon enough, and I want to more easily filter down to more recent issues.

Thanks for being early adopters of our tooling! We know that it can lead to issues like this being unresolved sometimes, but we're working hard on the new iteration of Form. 

Maybe take a look and let us know what you think?

https://tanstack.com/form

Best,

- Corbin
