### ISSUE TITLE
Validate all fields from top-level runValidation

### ISSUE THREAD

**Issue by JaceHensley** [TanStack/form#361]
I was looking through the API docs and `runValidation` from `useForm` says it doesn't run validation for all fields but to submit a feature request for this if it's needed.

I have a multi page form so I'd like to run all form validation when the user clicks to go to the next page run all field validations and set the fields with error as touched. 

Formik's top-level validate function returned an object that has a mapping from field names to their error message:

```ts
{
  'field-1': 'This field is required',
  'field-5': 'Please select at least 2 options'
}
```

So you would call `runValidation` and it returns all the errors in the form and then if you wanted to you could set meta for all the fields with errors.

```tsx
const {Form, runValidation, meta} = useForm()

<Form>
  <button 
    // Make it type of "button" because I want to control back from forwards
    type="button" 
    onClick={async () => {
      // Just guessing that runValidation would have to be await-ed because of possible async validation
      const errors = await runValidation()

      const keys = Object.keys(errors)
      const hasErrors = keys.length > 0

      keys.forEach(key => {
        setFieldMeta(key, prev => ({...prev, isTouched: true}))
      })

      // Handle blocking or allowing navigation
    }}
  >
    Previous Page
  </button>
  <button type="button" onClick={...}>Next Page</button>
</Form>


```

**Comment by tannerlinsley** [comment]
Yes, I think that would be one way to solve it. Async validation is where things existing API's in other tools are lacking, but it also allows them to be simpler. Since React Form is async by default, you would need to await the validation for each field like you said. Have you tried this yet?

**Comment by JaceHensley** [comment]
I haven't tried that cause the docs said runValidation didn't run the validation for each individual field just the form level validation

**Comment by joepuzzo** [comment]
This is unfortunately a fundamental down side to supporting async validation. That being said. If internally a promise.all was implemented to wait for all field level validation it would be possible.

**Comment by JaceHensley** [comment]
I think that's what formik is doing, cause their `validateForm` function (which is the equivalent to `runValidation`) always returns a promise that needs to be `await`-ed. I don't think that's a bad pattern.

**Comment by joepuzzo** [comment]
Remember formik is going to remove async validation tho. There is an issue out where jared palmer goes into detail

**Comment by tannerlinsley** [comment]
Yeah I’ve read it. Nice opinions, but I still think it’s just a challenge that can be solved with some good API design.

**Comment by joepuzzo** [comment]
Totally agree. That api design is the holy grail however. Needs to be done such that it adds little to no complexity

**Comment by tannerlinsley** [comment]
Sure. All I am saying is that I’m willing to find and make the trade offs required to get there. I won’t settle for just giving up on async. It’s there, people want it and expect it.

Tanner Linsley

**Comment by JaceHensley** [comment]
Ah okay I didn't realize they were planning on removing it. If you need any help with the effort let me, happy to help :)

**Comment by JaceHensley** [comment]
I was able to sort of get around this by setting `validatePristine: true` in `useField`, and then I disable the "Next" button when `useForm`'s `canSubmit` is false. So this would prevent users from progressing but it doesn't show the errors, which is fine for me for now at least :)

**Comment by crutchcorn** [comment]
Hey all, I'm closing this issue as it appears to be related to a version of the **old** non-current `@tanstack/react-form` and friend APIs. We're looking to 1.x soon enough, and I want to more easily filter down to more recent issues.

Thanks for being early adopters of our tooling! We know that it can lead to issues like this being unresolved sometimes, but we're working hard on the new iteration of Form. 

Maybe take a look and let us know what you think?

https://tanstack.com/form

Best,

- Corbin
