### ISSUE TITLE
swapValues error on nested fields

### ISSUE THREAD

**Issue by justisb** [TanStack/form#364]
Minimal example here:
https://codesandbox.io/s/react-form-basic-form-hooks-only-6muwk?fontsize=14&hidenavigation=1&theme=dark

To reproduce:
1. Add two nested "Nicknames"
2. Try to move them up/down using the controls, which calls swapValues on their indexes
3. Observe `str.replace is not a function` error

It looks like the fields get passed as an array like `['nicknames', '0']` and `['nicknames', '1']` in `swapFieldValues`:
https://github.com/tannerlinsley/react-form/blob/master/src/hooks/useForm.js#L386

But `getBy` calls `makePathArray` which expects a string here:
https://github.com/tannerlinsley/react-form/blob/master/src/utils.js#L35
https://github.com/tannerlinsley/react-form/blob/master/src/utils.js#L101

I'm not sure if the correct solution is passing in a string from `swapFieldValues` or to modify `makePathArray` to check if it's already an array.

**Comment by crutchcorn** [comment]
Hey all, I'm closing this issue as it appears to be related to a version of the **old** non-current `@tanstack/react-form` and friend APIs. We're looking to 1.x soon enough, and I want to more easily filter down to more recent issues.

Thanks for being early adopters of our tooling! We know that it can lead to issues like this being unresolved sometimes, but we're working hard on the new iteration of Form. 

Maybe take a look and let us know what you think?

https://tanstack.com/form

Best,

- Corbin
