### ISSUE TITLE
[Violation] Forced reflow while executing JavaScript

### ISSUE THREAD

**Issue by rgbskills** [TanStack/form#366]
I'm using react-form with https://github.com/JedWatson/react-select and the onChange event gets triggered when you type in other inputs within the form and it gets triggered as many times as the number of inputs you have in your form.

**Comment by crutchcorn** [comment]
Hey all, I'm closing this issue as it appears to be related to a version of the **old** non-current `@tanstack/react-form` and friend APIs. We're looking to 1.x soon enough, and I want to more easily filter down to more recent issues.

Thanks for being early adopters of our tooling! We know that it can lead to issues like this being unresolved sometimes, but we're working hard on the new iteration of Form. 

Maybe take a look and let us know what you think?

https://tanstack.com/form

Best,

- Corbin
