### ISSUE TITLE
No code coverage

### ISSUE THREAD

**Issue by KubaJastrz** [TanStack/form#371]
Hi, thanks for the awesome package. The API suits me best from all similar form utils, but I noticed there is no unit tests in the repo.

I can start working on this using @testing-library. If you have any other preferences, let me know.

**Comment by dasubermanmind** [comment]
Hey, this is a great idea. I'd like to help

**Comment by KubaJastrz** [comment]
@dasubermanmind, there haven't been any activity from maintainers for over a year. I'd recommend switching to another form library. I'm currently using [react-hook-form](https://react-hook-form.com/) and it's ok for me.

**Comment by crutchcorn** [comment]
Hey y'all! We're back and working on a fresh rewrite! 😱 

Would love to hear y'all's feedback on the new stuff:

https://tanstack.com/form/latest/docs/overview

That said, relevant to this ticket, we now have early versions of:

- [Integration tests for the framework-agnostic core](https://github.com/TanStack/form/blob/main/packages/form-core/src/tests/FormApi.spec.ts)
- [Type tests for the core](https://github.com/TanStack/form/blob/main/packages/form-core/src/tests/FieldApi.test-d.ts)
- [Integration tests for the React framework adapter, using Testing Library](https://github.com/TanStack/form/blob/main/packages/react-form/src/tests/useForm.test.tsx)

I'm going to be closing this ticket, but we absolutely still need (a lot of) help with adding more tests and test coverage prior to a v1 of the rewrite being released.

If this seems interesting to you, [drop in our Discord](https://tlinz.com/discord) and ping me in the `#form` channel and we can figure out how to divvy up work
