### ISSUE TITLE
Read fields error

### ISSUE THREAD

**Issue by mnemanja** [TanStack/form#375]
I have a field `items` which in turn has objects inside.
```ts
items: [
  {id: '1', someProp: 'foo'},
  {id: '2', someProp: 'bar'}
]
```

The properties of items are in error, but that error doesn't bubble up to the `items` field.

Would it be possible to somehow obtain the information about the fields in error on an upper level, aside from the field in error itself?

**Comment by crutchcorn** [comment]
Hey all, I'm closing this issue as it appears to be related to a version of the **old** non-current `@tanstack/react-form` and friend APIs. We're looking to 1.x soon enough, and I want to more easily filter down to more recent issues.

Thanks for being early adopters of our tooling! We know that it can lead to issues like this being unresolved sometimes, but we're working hard on the new iteration of Form. 

Maybe take a look and let us know what you think?

https://tanstack.com/form

Best,

- Corbin
