### ISSUE TITLE
formInstance.setValues does not take an updater function

### ISSUE THREAD

**Issue by rr-tommy-tan** [TanStack/form#376]
for `formInstance.setValues` the docs say `If a callback is passed, it will be given the previous value and be expected to return a new one, similar to React's setState callback style.`

currently, it does not take a callback as seen below.

code:
```
  const setValues = React.useCallback(
    values => {
      setState(old => ({
        ...old,
        values: values,
      }))
    },
    [setState]
  )
```

PR has been created to add the callback here:
https://github.com/tannerlinsley/react-form/pull/379

**Comment by crutchcorn** [comment]
Hey all, I'm closing this issue as it appears to be related to a version of the **old** non-current `@tanstack/react-form` and friend APIs. We're looking to 1.x soon enough, and I want to more easily filter down to more recent issues.

Thanks for being early adopters of our tooling! We know that it can lead to issues like this being unresolved sometimes, but we're working hard on the new iteration of Form. 

Maybe take a look and let us know what you think?

https://tanstack.com/form

Best,

- Corbin
