### ISSUE TITLE
[Feature Request]: useField instance returns label component.

### ISSUE THREAD

**Issue by smurrayatwork** [TanStack/form#380]
It'd be nice if useField could optionally return a `FieldLabel` component that references the field with `htmlFor` automatically. FieldLabel would render a `<label>` element. The field would need to set its `id` attribute for `htmlFor` as well. Perhaps it could use the field path?

```
const {
    FieldLabel,
    meta: { error, isTouched, isValidating },
    getInputProps
  } = useField(field, fieldOptions);
return (
  <>
    <FieldLabel />
    <input {...getInputProps()} />
  </>
);
```

**Comment by crutchcorn** [comment]
Hey all, I'm closing this issue as it appears to be related to a version of the **old** non-current `@tanstack/react-form` and friend APIs. We're looking to 1.x soon enough, and I want to more easily filter down to more recent issues.

Thanks for being early adopters of our tooling! We know that it can lead to issues like this being unresolved sometimes, but we're working hard on the new iteration of Form. 

Maybe take a look and let us know what you think?

https://tanstack.com/form

Best,

- Corbin
