### ISSUE TITLE
Insert a new value in the middle of an array-like field

### ISSUE THREAD

**Issue by tmporterSGSI** [TanStack/form#381]
Assume I have the following array-like field

```
"friends": [ "James", "Julie", "John" ]
```

and I want to insert a fourth value between "James" and "Julie".

What would be the recommended way to accomplish this without calling `pushFieldValue()` followed by multiple `swapFieldValue()` calls?

**Comment by tmporterSGSI** [comment]
I suppose one option would be to use `setFieldValue()`'s callback argument to manually splice the new value into the middle of the array.

**Comment by crutchcorn** [comment]
Hey all, I'm closing this issue as it appears to be related to a version of the **old** non-current `@tanstack/react-form` and friend APIs. We're looking to 1.x soon enough, and I want to more easily filter down to more recent issues.

Thanks for being early adopters of our tooling! We know that it can lead to issues like this being unresolved sometimes, but we're working hard on the new iteration of Form. 

Maybe take a look and let us know what you think?

https://tanstack.com/form

Best,

- Corbin
