### ISSUE TITLE
Typescript module @types/react-form does not include hooks

### ISSUE THREAD

**Issue by vimtor** [TanStack/form#382]

**Comment by goncedillo** [comment]
Same problem here. I didn't see anything related to TS in documentation.

**Comment by mitorski** [comment]
Same here.

**Comment by colin-ggd** [comment]
Any update on this?

**Comment by azat-io** [comment]
+1

**Comment by employee451** [comment]
While waiting for this to be fix, I've removed the @types/react-form package and made a `declarations.d.ts` file with these contents:

    declare module 'react-form' {
        var reactForm: {
    	    Form: any
    	    splitFormProps: any
    	    useField: any
    	    useForm: any
        }
        export = reactForm
    }

In no way is this ideal, but it works

**Comment by Toliak** [comment]
Hello! I have created a [Pull Request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50864) to the DefinitelyTyped repository. Please, review it.

**Comment by crutchcorn** [comment]
Hey all, I'm closing this issue as it appears to be related to a version of the **old** non-current `@tanstack/react-form` and friend APIs. We're looking to 1.x soon enough, and I want to more easily filter down to more recent issues.

Thanks for being early adopters of our tooling! We know that it can lead to issues like this being unresolved sometimes, but we're working hard on the new iteration of Form. 

Maybe take a look and let us know what you think?

https://tanstack.com/form

Best,

- Corbin
