### ISSUE TITLE
API Documentation issues

### ISSUE THREAD

**Issue by Toliak** [TanStack/form#384]
1. There are two `isValid` properties in **Form Instance** -> **meta**  
  [The first entrance](https://github.com/tannerlinsley/react-form/blame/master/docs/api.md#L59)  
  [The second entrance](https://github.com/tannerlinsley/react-form/blame/master/docs/api.md#L65)

2. `See Field Scoping for more information` link does not work  
  [Entrance](https://github.com/tannerlinsley/react-form/blame/master/docs/api.md#L191)

3. `Validation Example` does not work properly  
  Mistake on line 187: should be `disabled`, not `disable`  
  Wrong behavior screenshot: ![](https://i.imgur.com/eIu4KP4.png) 
  [Examples MD file](https://github.com/tannerlinsley/react-form/blob/7c187f2e1fc13b437f0e21c3747cf6ac56c51f6c/docs/examples.md)  
  [Example link](https://codesandbox.io/s/react-form-demo-q9mgm)

**Comment by crutchcorn** [comment]
Hey all, I'm closing this issue as it appears to be related to a version of the **old** non-current `@tanstack/react-form` and friend APIs. We're looking to 1.x soon enough, and I want to more easily filter down to more recent issues.

Thanks for being early adopters of our tooling! We know that it can lead to issues like this being unresolved sometimes, but we're working hard on the new iteration of Form. 

Maybe take a look and let us know what you think?

https://tanstack.com/form

Best,

- Corbin
