### ISSUE TITLE
Failed to minify the code from this file: #create-react-app

### ISSUE THREAD

**Issue by akkyjumbade** [TanStack/form#387]
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/react-form/dist/index.es.js:168:22 

Read more here: http://bit.ly/2tRViJ9
<img width="971" alt="Screenshot 2021-07-02 at 7 38 10 PM" src="https://user-images.githubusercontent.com/12668753/124287104-42965a00-db6d-11eb-9b7a-80410633f4b9.png">

**Comment by akkyjumbade** [comment]
### System info
macOs M1 (MBP)
node: v16.2.0
npm: 7.13.0

**Comment by crutchcorn** [comment]
Hey all, I'm closing this issue as it appears to be related to a version of the **old** non-current `@tanstack/react-form` and friend APIs. We're looking to 1.x soon enough, and I want to more easily filter down to more recent issues.

Thanks for being early adopters of our tooling! We know that it can lead to issues like this being unresolved sometimes, but we're working hard on the new iteration of Form. 

Maybe take a look and let us know what you think?

https://tanstack.com/form

Best,

- Corbin
