### ISSUE TITLE
Field initial values are "undefined"

### ISSUE THREAD

**Issue by wmadden** [TanStack/form#400]
### Describe the bug

Despite providing `defaultValues`, the initial values of simple string fields are `undefined`.

This is occurring in the example CodeSandbox from the @tanstack/form docs: https://codesandbox.io/p/sandbox/github/tannerlinsley/react-form/tree/main/examples/react/simple

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/github/tannerlinsley/react-form/tree/main/examples/react/simple

### Steps to reproduce

1. Initialize a field with a default value of ""
2. Render the form

### Expected behavior

The input should be empty

### How often does this bug happen?

None

### Screenshots or Videos

![image](https://github.com/TanStack/form/assets/12165/aa499325-2d8d-4df9-8237-8dbbfbd56b7d)

### Platform

Mac
Chrome 
react-form@0.0.11

### Tanstack Form adapter

None

### TanStack Form version

0.0.11

**Comment by kairosense** [comment]
`Maximum call stack size exceeded`  When emptied the input value

![image](https://github.com/TanStack/form/assets/138148800/114953a4-bf1b-4340-ab50-dc65d48e736c)

**Comment by zeeeeby** [comment]
> `Maximum call stack size exceeded` When emptied the input value
> 
> ![image](https://user-images.githubusercontent.com/138148800/252245325-114953a4-bf1b-4340-ab50-dc65d48e736c.png)

@crutchcorn Please look at  "maximum call stack" error. It's very disturbing.

**Comment by crutchcorn** [comment]
The original issue on `undefined` initial values should be solved now.

As for the "Maximum call stack" error, I'm investigating and resolving here:

https://github.com/TanStack/form/issues/406
