### ISSUE TITLE
Documentation error with "Schema-based Validation"

### ISSUE THREAD

**Issue by TzviPM** [TanStack/form#426]
### Describe the bug

The docs indicates that "Schema-based Validation" is "Supported and documented, but requires extra user-code to implement". However, there is no documentation on the website or github repo for how to use schema-based validation.

### Your minimal, reproducible example

https://tanstack.com/form/latest/docs/comparison

### Steps to reproduce

1. Go to https://tanstack.com/form/latest/docs/comparison
2. look at "Schema-based Validation" under "TanStack Form"

### Expected behavior

The feature is supported and documentation is provided, or else it is indicated "Not officially supported or documented."

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/form/assets/1950680/0cc449e7-1cfc-4d79-84d4-e56a2de637a0)

### Platform

Windows 11 on Microsoft Edge

### Tanstack Form adapter

None

### TanStack Form version

latest

**Comment by crutchcorn** [comment]
This library is broadly under development and documentation efforts - rest assured that all of the features in this document will land prior to a v1 launch :) 

Specifically, we're wanting to use an adapter system akin to RHF to add schema based validation

Closing for now, as this is known work we need to tackle
