### ISSUE TITLE
Change from single error message to object or array of errors

### ISSUE THREAD

**Issue by crutchcorn** [TanStack/form#431]
Right now, we only have a single error per field. This seems like it might limit the UX of any app using TanStack Form.

Instead, I'd like to change our validators to return an object or array of errors:

```ts
errorMap = {
    onChange: ValidationError,
    onMount: ValidationError,
    onBlur: ValidationError,
}
```

Or:

```ts
errors: [] // As many errors as show up in `onChange`, `onMount`, `onBlur`
```

If anything, we may want to provide both to the `FieldAPI` in our react adapter. Something like:

```tsx
<form.Field
  name="firstName"
  children={(field) => {
    const errArr = field.state.meta.errors // Array of errors
    const errMap = field.state.meta.errorMap; // Object of errors
    const onChangeErr = errMap?.onChange; // string | undefined | null
  }}
/>
```

Where `errors` is derived from `errorMap` as a derived value

**Comment by CheRayLiu** [comment]
Going to work on this one. Could I get assigned to this? 🙏

**Comment by crutchcorn** [comment]
Absolutely! Thank you for contributing 😊
