### ISSUE TITLE
Forms can be submitted having empty pristine mandatory fields

### ISSUE THREAD

**Issue by Arian94** [TanStack/form#469]
### Describe the bug

If a form is pristine, they can be submitted whether or not a field is required. This is ridiculous.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/agitated-waterfall-pvq8zs?embed=1&file=%2Fsrc%2Findex.tsx%3A39%2C1

### Steps to reproduce

create a simple form.

### Expected behavior

submit button must be disabled if there is a pristine required field.

### How often does this bug happen?

None

### Platform

MACOS

### Tanstack Form adapter

None

### TanStack Form version

^0.3.6

**Comment by jcorralfox** [comment]
I think this is expected behaviour, have you tried this?
`<form.Field
    name="firstName"
    onSubmitAsync={async (value) => {
      return (
        !value && 'WAT'
      )
    }}`

**Comment by crutchcorn** [comment]
Closing, as this is expected behavior perf @jcorralfox 

Further:

> This is ridiculous.

C'mon @Arian94. Please be more respectful towards maintainers and projects in the future. This is disrespectful and non-contributive to the conversation. We're not even 1.0 yet.

**Comment by Arian94** [comment]
> I think this is expected behaviour, have you tried this?
> 
> ```
> <form.Field
>     name="firstName"
>     onSubmitAsync={async (value) => {
>       return !value && "an error message"
>     }}
> ...rest of code
> ```

I have tried it. It does not work because when you click on Submit button it does show you the field error but it will not let you Submit anymore.

**Comment by Arian94** [comment]
> Closing, as this is expected behavior per @jcorralfox's comment
> 
> Further:
> 
> > This is ridiculous.
> 
> C'mon @Arian94. Please be more respectful towards maintainers and projects in the future. This is disrespectful and non-contributive to the conversation. We're not even 1.0 yet.

This is standard writing for developers. Haven't you talked with big tech guys? Maybe you should talk to Linus.

The thing that I am using your new library for a serious project shows my respect, don't you think so?

Besides, you shouldn't have closed this issue since it's still not fixed.

**Comment by crutchcorn** [comment]
> This is standard writing for developers.

In no world that I want to live in is this standard writing for developers. If this is true for your teams; I authentically urge you to seek better environments to work within.

**Comment by ThatOneCalculator** [comment]
It seems that Arian is just a troll. By no means should their behavior be considered "standard writing". https://github.com/webpack/webpack/issues/12120

**Comment by rustedwolf** [comment]
Well I'm having the same issue as well, that's why I'm here reading this drama trying to find any useful information.

The year has passed and this kinda basic issue still persists. It really would be nice if there was some kind of check implemented for required fields. IDK, maybe add validation without error messaging on initialization?
