### ISSUE TITLE
[Docs] Guide about custom form controls

### ISSUE THREAD

**Issue by juliendelort** [TanStack/form#479]
All our examples show how to use the library with simple form elements (inputs etc…) but we should also show how to use this library with custom/non standard elements. 

The page can cover the following topics:

- How do I use this with a custom select component, like [react-select](https://react-select.com/home)?
- How do I make sure that the changes are saved in the form state, that the validation happens and that I am able to set the value via the form API?

**Comment by crutchcorn** [comment]
This feels a bit like a duplicate of #473, what do you think?

**Comment by juliendelort** [comment]
yeah I agree. Feel free to close this one in favor of that one!
