### ISSUE TITLE
FormApi.reset seems to break a form

### ISSUE THREAD

**Issue by Christian24** [TanStack/form#495]
### Describe the bug

Hi,

I am currently working on a prototype Lit wrapper for Tanstack Form. My prototype shows problems with `FormApi.reset()`. This is the initial state of the form:

```json
{
  "values": {},
  "fieldMeta": {
    "firstName": {
      "isValidating": false,
      "isTouched": false,
      "touchedErrors": [],
      "errors": [],
      "errorMap": {}
    },
    "lastName": {
      "isValidating": false,
      "isTouched": false,
      "touchedErrors": [],
      "errors": [],
      "errorMap": {}
    },
    "color": {
      "isValidating": false,
      "isTouched": false,
      "touchedErrors": [],
      "errors": [],
      "errorMap": {}
    },
    "employed": {
      "isValidating": false,
      "isTouched": false,
      "touchedErrors": [],
      "errors": [],
      "errorMap": {}
    }
  },
  "canSubmit": true,
  "isFieldsValid": true,
  "isFieldsValidating": false,
  "isFormValid": true,
  "isFormValidating": false,
  "isSubmitted": false,
  "isSubmitting": false,
  "isTouched": false,
  "isValid": true,
  "isValidating": false,
  "submissionAttempts": 0,
  "formValidationCount": 0
}
```

After calling `FormApi.reset()` the state is:

```json
{
  "values": {},
  "fieldMeta": {},
  "canSubmit": true,
  "isFieldsValid": true,
  "isFieldsValidating": false,
  "isFormValid": true,
  "isFormValidating": false,
  "isSubmitted": false,
  "isSubmitting": false,
  "isTouched": false,
  "isValid": true,
  "isValidating": false,
  "submissionAttempts": 0,
  "formValidationCount": 0
}
```

Whenever a field changes Tanstack form then crashes at:  https://github.com/TanStack/form/blob/84e257f310ab1eedb4cc185199c0a41e4f701144/packages/form-core/src/FieldApi.ts#L201. This happens because `errorMap` is undefined. 

### Your minimal, reproducible example

https://stackblitz.com/github/christian24/tanstack-form-lit-prototype?file=src%2Findex.ts

### Steps to reproduce

1. Click on reset
2. Change a field

Error appears in console. 

### Expected behavior

I expect reset to not break the form. 

### How often does this bug happen?

Every time

### Platform

- Mac OS
- Edge
- latest

### Tanstack Form adapter

None

### TanStack Form version

0.61.0

### TypeScript version

^5.0.2

### Additional context

FYI @crutchcorn :)

**Comment by vikaskumar89** [comment]
@crutchcorn 
can you assign this to me please

**Comment by I-MirzaBaig** [comment]
Has anyone found the outcome of this bug?
Or Has it being resolved?

**Comment by Christian24** [comment]
I think @vikaskumar89 is working on fixing it.

**Comment by barsikus007** [comment]
any updates?

**Comment by vikaskumar89** [comment]
Hi,
I am not working on this any longer. Feel free to pick this up.

**Comment by masylum** [comment]
any workaround?

**Comment by crutchcorn** [comment]
This should be fixed in the latest version
