### ISSUE TITLE
DeepKeys produces keys incompatible with DeepValue

### ISSUE THREAD

**Issue by rodogir** [TanStack/form#569]
### Describe the bug

I noticed the bug when trying to use the `Field` component with a static name that points to a property inside of an array (e.g. `friends.0.name`). The useField hook and Field component will claim that the name prop is invalid, even though they function correctly. This is due how DeepKeys is defined. Further, I also noticed that DeepValue correctly handles array keys.

### Your minimal, reproducible example

[codesandbox](https://codesandbox.io/p/devbox/young-surf-zls8z5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrakyj7k0007356f2dfdvw8h%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrakyj7k0002356fuvoogvwz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrakyj7k0004356flwv76ust%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrakyj7k0006356ffu7z3jq3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B52.81181552837657%252C47.18818447162343%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrakyj7k0002356fuvoogvwz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrakyj7k0001356fquthikwl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrakyj7k0002356fuvoogvwz%2522%252C%2522activeTabId%2522%253A%2522clrakyj7k0001356fquthikwl%2522%257D%252C%2522clrakyj7k0006356ffu7z3jq3%2522%253A%257B%2522id%2522%253A%2522clrakyj7k0006356ffu7z3jq3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrakyj7k0005356facw84t2x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrakyj7k0005356facw84t2x%2522%257D%252C%2522clrakyj7k0004356flwv76ust%2522%253A%257B%2522id%2522%253A%2522clrakyj7k0004356flwv76ust%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrakyj7k0003356f0zss2a6o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrakyj7k0003356f0zss2a6o%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

**DeepKeys problem**

1. Go to /src/example.spec.ts
2. Look at the code and notice that type issues when trying to use `DeepValue` with `DeepKeys`

**To see that Field works with array keys:**

1. Run the linked codesanbox
2. You will see 2 input fields, change second one ("Robin") to whatever you want.
3. Hit the submit button
4. Check the console and verify that the values are as expected.
5. The source code is under /src/App.tsx

### Expected behavior

I expect DeepKeys to produce keys that are compatible with DeepValue. Also, I should be able to use `Field` with a key containing array indexes (e.g. `friends.${number}.name`).

### How often does this bug happen?

Every time

### Platform

It's a type issue and platform independent.

### Tanstack Form adapter

None

### TanStack Form version

0.13.3

### TypeScript version

5.2.2

**Comment by crutchcorn** [comment]
_Technically_ you're not supposed to use `DeepKeys` and `DeepValue` outside of the internals of the library. They're exposed because they're how we build out the types and have to be to make the types "portable".

Also, the API you're trying to use with a number being part of the `name` isn't valid in framework adapters for this reason (IIRC). There's likely some work we need to do to clarify this (even probably changing the API).

**Comment by rodogir** [comment]
Thanks for the clarification.

I'd like to provide some context for you to understand where we are coming from. We are building reusable, form-connected and type-safe input components. Here's an usage example:

```tsx
function Example() {
  const form = useForm({
    defaultValues: {
      firstName: 'John',
      lastName: 'Doe',
      age: 42,
    }
  });

  return (
    <form>
      <FormTextField form={form} name="firstName" />
      <FormTextField form={form} name="lastName" />
      <FormNumberField form={form} name="age" />
    </form>
  );
}
```

We rely on DeepKeys and DeepValue to enforce type safety. For example, FormTextField accepts only names with string values, while FormNumberField is restricted to names with number values. This greatly improves our DX.

However, since DeepKeys and DeepValue are internal, I'm concerned about the sustainability of our approach. Are there alternative, officially supported methods for achieving similar levels of type safety with form components?

**Comment by crutchcorn** [comment]
Agreed that this usage is the right way to go. It's how our docs will eventually encourage people to use TanStack Form.

Let's chat more in [our Discord](https://tlinz.com/discord) about how we can make this process easier and smoother for you (and others!). It might mean continuing to rely on `DeepKeys` and `DeepValue` for now but we introduce a more stable API in the future.

If nothing else, it'll help us shape what our docs should look like for this scenario.

**Comment by crutchcorn** [comment]
This issue with the typings should not occur anymore. However, ignoring that, we'll be working on documenting in-house library usage prior to 1.x

Closing since we should discuss that in a different issue
