### ISSUE TITLE
Nested array doesn't work in react strict mode

### ISSUE THREAD

**Issue by Balastrong** [TanStack/form#655]
### Describe the bug

An error is thrown on component mount when using an array inside an object and the app is inside `React.StrictMode`

The component is not rendered.

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-form-an5lkt?file=package.json,src%2Findex.tsx

### Steps to reproduce

1. Have a nested structure like in the MRE
2. Have your react app on strict mode
3. Mount the component

### Expected behavior

The component loads

### How often does this bug happen?

Every time

### Platform

macOS but also on stackblitz

### TanStack Form adapter

react-form

### TanStack Form version

v0.18.0

### Additional context

The error message is 
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys
```

If I'm not mistaken, it seems that during the duplicate render caused by strict mode, `state.value` is undefined here:
https://github.com/TanStack/form/blob/39848e3654e6b47acbf91e30858fb183493e5041/packages/react-form/src/useField.tsx#L93

**Comment by crutchcorn** [comment]
This issue should be fixed with the newest version of TanStack Form
