### ISSUE TITLE
Missing error when validating via form options instead of via field

### ISSUE THREAD

**Issue by bennettdams** [TanStack/form#678]
### Describe the bug

When using the (Zod) validator on the form options (passing to `useForm`) instead of using it directly on the field, there is no entry in the `errors`/`touchedErrors` array.

## Works (directly on field)

<img width="391" alt="image" src="https://github.com/TanStack/form/assets/29319414/b9e4352a-b2d6-47fb-bc19-49a118a3712a">

## Doesn't work (passing to `useForm`)

<img width="340" alt="image" src="https://github.com/TanStack/form/assets/29319414/d07dc75d-e888-4819-b707-29757ddb5f73">

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/nifty-voice-rzmgm9?file=%2Fsrc%2Findex.tsx

### Steps to reproduce

There are two forms in the repro example.
The first form uses a validator on the `form.Field`. Everything works as expected.
The second form uses a validator on the form options. Now, there is no error.

### Expected behavior

Validation errors are put on the `errors`/`touchedErrors` field, no matter where validation took place.

### How often does this bug happen?

Every time

### Platform

-

### TanStack Form adapter

react-form

### TanStack Form version

v0.19.1

### TypeScript version

v5.4.5

**Comment by crutchcorn** [comment]
Away from a computer right now. Are you checking against the field errors or the form errors. This is a bit confusing, but form validation like this doesn't set field errors, it sets form errors

**Comment by bennettdams** [comment]
> Are you checking against the field errors or the form errors.

Yep, was using the `FieldInfo` helper from the examples.

> it sets form errors

You're right, the validation message exists on `field.form.state.errors`, thanks!

> This is a bit confusing

I have to agree that this is confusing, as one would always need to look for multiple places.
Also, it seems that the form has no `touchedErrors` like a `Field` has?

Helper component for reference:
```tsx
function FieldInfo({ field }: { field: FieldApi<any, any, any, any> }) {
  // This is empty when using the "form" validator (but not for the "field" validator)
  console.log("field touchedErrors", field.state.meta.touchedErrors);
  // ...but not empty for the form's `errors`
  console.log("form errors", field.form.state.errors);
  return (
    <>
      {field.state.meta.touchedErrors.length === 0 ? (
        "No errors"
      ) : field.state.meta.touchedErrors ? (
        <em>{field.state.meta.touchedErrors}</em>
      ) : null}
    </>
  );
}
```

**Comment by crutchcorn** [comment]
FWIW we're actually planning on removing `touchedErrors` 😅

Also, we're gonna make the story of form->field validation easier here:

https://github.com/TanStack/form/pull/656

Closing as both are a WIP, but thanks for the feedback and detailed report 😇
