### ISSUE TITLE
server actions example errors when using zod adapter

### ISSUE THREAD

**Issue by juliusmarminge** [TanStack/form#690]
### Describe the bug

When adding a validator adapter to the next server actions example it starts erroring trying to read the validator. Maybe I'm setting it up incorrectly but i just added the adapter

### Your minimal, reproducible example

https://github.com/juliusmarminge/tanstack-form-zod-server-actions

### Steps to reproduce

Install deps, start server and try to submit:

https://github.com/TanStack/form/assets/51714798/beacc19f-c105-48cb-aba8-9068389b7f0e

### Expected behavior

it to work

### How often does this bug happen?

Every time

### Platform

Don't think it's relevant but..

- Latest macOS 
- Latest Arc

### TanStack Form adapter

react-form

### TanStack Form version

0.19.4

### TypeScript version

5.4.2

**Comment by crutchcorn** [comment]
I think I know what's going on - oversight on my part when implementing the SSR stuff.

I'll investigate on this soon

**Comment by crutchcorn** [comment]
This should work fully now
