### ISSUE TITLE
Example for array usage lacks mode="array"

### ISSUE THREAD

**Issue by tophercf** [TanStack/form#711]
### Describe the bug

The full example does not include the mode="array" for the array form field example. I think this is needed: 
[git@github.com:TanStack/form.git](https://github.com/TanStack/form/blob/main/docs/framework/react/guides/arrays.md#full-example)

### Your minimal, reproducible example

- go to linked documentation and see the issue

### Steps to reproduce

1. go to the linked array doc 
2. see full example section
3. see the lack of the mode="array" for the full example

### Expected behavior

I would expect the described implementation for array form elements to be shown in the full example.

### How often does this bug happen?

None

### Platform

platform agnostic

### TanStack Form adapter

None

### TanStack Form version

latest

### TypeScript version

n/a

**Comment by crutchcorn** [comment]
CC @Balastrong any chance you could PR this for us? 😅
