### ISSUE TITLE
Type Error onServerValidate async

### ISSUE THREAD

**Issue by CoachNooB** [TanStack/form#737]
### Describe the bug

I got red squigly line when putting async in onServerValidate. But it run normally in runtime.
Type Promise <string | undefined> is not assignable to type ValidationError

### Your minimal, reproducible example

https://www.typescriptlang.org/play/?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydaiKKEEeBkGgAb1A7EEkAAYlTEKAAL44thsgBEAAFUGZBILYPFgJNYKhSslWTyANzBBCcYU41mgAC89MZLLIiAAFDTFCUStxIMkGFFUAA1BjQdiQfKgQ3Gl39BjIR08nlG43s3jBF2NYjfPRkG3QCjcOoOsTHcygA2gHS2+0cgCUGoAfE6fa7QCoACIYCpx2CgYNkUOgcORuoNTi5jmKdlp4IqHDNDxkLyIKnOYHsGhfNxmZjsBjMSD8WAR0ViYF6EReHkAUVW7oW+h5SWxPPADlQAHJhAA5SASHlBFQAeS+ZHejP4k6OgupkFc0jwoCcvZ0wyw+goAgiDQsIlzDhIVLRCIBgcNiCxMKwHA8EEihAA

### Steps to reproduce

1. Put async in the onServerValidate
2. Got Type error

### Expected behavior

No Type Error.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/form/assets/55129369/05c5c8d2-285b-40d9-a840-ca06fce01d6a)

### Platform

- OS: Windows
- Browser: OperaGX

### TanStack Form adapter

react-form

### TanStack Form version

v0.20.2

### TypeScript version

v5.4.2

**Comment by my-slab** [comment]
I had a crack at fixing it in https://github.com/TanStack/form/pull/822.

**Comment by Balastrong** [comment]
Implemented in #855
