### ISSUE TITLE
[DOCS]: Rewrite The Reference Docs For Users

### ISSUE THREAD

**Issue by tobySolutions** [TanStack/form#749]
Rewrite/replace the [reference docs](https://tanstack.com/form/latest/docs/reference/formApi) for the Tanstack APIs and make sure they are standard and intuitive enough for users and external users.

A preferable way to go about it will be to use [TSdoc](https://tsdoc.org/) to auto-generate them 😁.

Related to https://github.com/TanStack/form/issues/746.

**Comment by crutchcorn** [comment]
Please not that work on this has already begun here:

https://github.com/TanStack/form/pull/735

**Comment by tobySolutions** [comment]
> Please not that work on this has already begun here:
> 
> https://github.com/TanStack/form/pull/735

Oh, of course no problem at all 🤲.
