### ISSUE TITLE
form is throwing an error in react native

### ISSUE THREAD

**Issue by noahkurz** [TanStack/form#774]
### Describe the bug

When following the documentation I received the error: Invariant Violation: View config getter callback for component form must be a function (received undefined). Make sure to start component names with a capital letter.

When I downgrade the library to 0.13.5 and use <form.Provider> The error resolves. 

Am I doing something wrong? 

### Your minimal, reproducible example

https://snack.expo.dev/WRkKekvP4XXMTuUBo1FUy

### Steps to reproduce

Start the app and the error will show

### Expected behavior

As a user I expected the page to load but it currently does not. 

### How often does this bug happen?

Every time

### Platform

- RN Expo

### TanStack Form adapter

None

### TanStack Form version

5.22.2

**Comment by crutchcorn** [comment]
Oh I see what's wrong. Remove `<form>`. That's only for HTML, which is not present in React Native

**Comment by noahkurz** [comment]
Then this error shows up.  Error: You are trying to use the form API outside of a form!

**Comment by noahkurz** [comment]
Worked. Thank you.

**Comment by whoiscarlo** [comment]
Thank you for this!
