### ISSUE TITLE
Default value differs from pushValue

### ISSUE THREAD

**Issue by derseitenschneider** [TanStack/form#780]
### Describe the bug

I'm using tanstack form now for two days and really enjoy working with it. I wanted to use it for a semi complex form, where the user can create new students. The idea is that you can create either one or multiple students in a single form, depending on your needs. 

So far i managed to create said behaviour with an Array of students, just as mentioned in the docs.

Since i want to display one row by default when the component renders, I created a defaultStudent and put it in the formOptions as a default Value for the students array. And whenever the user clicks add more, another row is added. This time i use the field.pushValue to add another student. I base that again on defaultStudent, but hence it being an object, i spread the default student in a new object.

Whats strange is, is that as soon as I log the values, the first row created via the defaultValues in the formOptions has all the object properties. However the added row has only properties when a field is filled. If I therefor add a second row so I have two rows, leave all fields empty and log the result on submit in the console, i get one Object with the default Student values and one completely empty.

Im not sure this is the intended behaviour. But ofc there's also potential for me getting something wrong here.
Apologies if this is the case, no intention to spam the issues here. 

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-uxd1ri?file=src%2FApp.tsx

### Steps to reproduce

1. Go to Stackbliz link
2. Open preview in new tab to see also the console.logs
3. Click add row
4. Click save and check console

### Expected behavior

I'm expecting both objects to look the same. I understand that it might be intentional to store only actually entered data in the returned object but not one with empty data, one without.

### How often does this bug happen?

Every time

### Platform

- macOS
- Chrome 126.0.6478.116

### TanStack Form adapter

react-form

### TanStack Form version

v0.23.3

### TypeScript version

v4.9.3

**Comment by Balastrong** [comment]
Thank you for the detailed issue!

To me it seems you're doing everything fine, we have some issues with arrays and StrictMode.
If you disable it from your `main.tsx` it should work for now.

**Comment by felipesere** [comment]
I have a very similar issue using `pushValue`. Of the 3 properties that I set on an ingredient (this app manages recipes & shoppinglists) 2 make it through, and the last one has its value once and on the second render of `<StrictMode />` gets lots, i.e. undefined.

Not really sure how to narrow this down?

**Comment by Balastrong** [comment]
The underlying issue is related to the mounting/unmounting of the fields.

You can also handle this with the `preserveValue` flag in your subfields. In the exaple of this issue it would be:
```tsx
<form.Field name={`students[${i}].firstName`} preserveValue>
...
</form.Field>
```

We're internally discussing about the future of that flag, if enabling it by default to begin with.

**Comment by derseitenschneider** [comment]
> The underlying issue is related to the mounting/unmounting of the fields.
> 
> You can also handle this with the `preserveValue` flag in your subfields. In the example of this issue it would be:
> 
> ```tsx
> <form.Field name={`students[${i}].firstName`} preserveValue>
> ...
> </form.Field>
> ```
> 
> We're internally discussing about the future of that flag, if enabling it by default or removing it entirely.

Thanks @Balastrong! Looks like this solved it for me. Much appreciate also the quick response time.

**Comment by crutchcorn** [comment]
preserveValue is now defaulted to true and the option was removed in 0.24
