### ISSUE TITLE
allow to reset form with new values

### ISSUE THREAD

**Issue by crutchcorn** [TanStack/form#785]
### Discussed in https://github.com/TanStack/form/discussions/596

<div type='discussions-op-text'>

<sup>Originally posted by **schiller-manuel** February  8, 2024</sup>
After form submission I want to keep the form open and make the form pristine again, but don't want to lose the current values.

Inspiration: In RHF this is possible via calling `reset` with new values: https://www.react-hook-form.com/api/useform/reset/</div>

**Comment by vara855** [comment]
@crutchcorn Hi. I'm wanna to contribute. Can you assign it to me?

**Comment by Balastrong** [comment]
Done in #791
