### ISSUE TITLE
Missing nested object values when using React StrictMode and `pushValue`

### ISSUE THREAD

**Issue by chidiwilliams** [TanStack/form#787]
### Describe the bug

Originally posted in https://github.com/TanStack/form/issues/704#issuecomment-2194542516.

When using a nested object within array form field, adding a new item using `pushValue` produces missing form fields.

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-form-ien81g?file=src%2Findex.tsx

### Steps to reproduce

Starting from the array example in the docs:

1. Wrap App in StrictMode.
2. Clicking on the "Add person" button three times results in `[{"age":0},{"age":0},{"name":"","age":0}]`. (Note the missing `name` field in the all but the last person.) 

### Expected behavior

As a user, I expected clicking on the "Add Person" button to result in three well-formed `{name: "", age: 0}` persons.

### How often does this bug happen?

Every time

### Platform

Chrome Version 126.0.6478.63 (Official Build) (x86_64)

### TanStack Form adapter

None

### TanStack Form version

v0.24.1

**Comment by crutchcorn** [comment]
This is now fixed in `0.24.2`. Sorry about that!
