### ISSUE TITLE
stackblitz example on landing page has typescript type errors

### ISSUE THREAD

**Issue by Huilensolis** [TanStack/form#807]
### Describe the bug

the landing page of tenstack form (https://tanstack.com/form/latest) has a stickblitz example at the bottom of the landing page.

it has typescript type errors (I did not change the code, its all default)
![image](https://github.com/TanStack/form/assets/113150193/d8b1e2ff-de4a-4970-af70-10d68a7bfbb6)

### Your minimal, reproducible example

https://stackblitz.com/fork/github/tanstack/form/tree/main/examples/react/simple?preset=node

### Steps to reproduce

1. scroll to the bottom of the code, t form.subscribe
2. see typescript errors.

### Expected behavior

to have no typescript errors

### How often does this bug happen?

Every time

### Platform

- browser: brave

### TanStack Form adapter

react-form

### TanStack Form version

0.25.1

### TypeScript version

idk

### Additional context

i cant fork the stackblitz project because stackblitz has blocked my browser (idk why. I have never used it)

**Comment by crutchcorn** [comment]
This is because the editor version of TypeScript that StackBlitz uses has a known bug with our codebase. There's nothing we can do to fix this issue until SB solves it.
