### ISSUE TITLE
ReactFormApi typing not exposed

### ISSUE THREAD

**Issue by frankkluijtmans** [TanStack/form#824]
### Describe the bug

In my React app I'm passing down instances of `FormApi` in a couple of places where I'll use some of the props that are added on top of it in `ReactFormApi`. I see that this `ReactFormApi` was added here https://github.com/TanStack/form/commit/145e0a90c738633e0a05b2604bd34d6e9ef29afa#diff-71307ac787e0ed388c8e67d3821dce46c1753ef4cca87f9e2c4b225d3bd30681. 

Since this type is not exposed I'm unable to properly type the `FormApi` instance I'm passing down in the props. Since there doesn't seem to be a replacement for it I get the feeling that exposing this type might've simply been overlooked 😅 

### Your minimal, reproducible example

[CodeSandbox](https://codesandbox.io/p/sandbox/great-smoke-cmqsfp?file=%2Fsrc%2FApp.tsx)

### Steps to reproduce

After upgrading from < 24.3 to 24.3 >

1. Pass down FormApi instance in component props.
2. Get TS error for `form.Subscribe`, `form.Field` etc.

### Expected behavior

The ability to import `ReactFormApi` typings.

### How often does this bug happen?

None

### Platform

Any platform

### TanStack Form adapter

None

### TanStack Form version

v0.25.3

### TypeScript version

5.5.2

**Comment by Balastrong** [comment]
You can temporarily get that with `ReturnType<typeof useForm<TFormData>>` with `TFormData` being your form schema, but we're indeed planning to expose `ReactFormApi` soon.

Actually, we're working on APIs specifically to build custom wrapper to form fields :D

**Comment by crutchcorn** [comment]
@frankkluijtmans since you're doing stuff in your codebase to internalize TanStack Form - we'd love your feedback on this PR example project:

https://github.com/TanStack/form/pull/825/files#diff-b2e0803ded7363bf3432f160f7c7f6e9bf4f982ad13b08ecb4789c228774f956

We're planning on making this the official way of doing what you're doing. 

What do you think?

**Comment by Balastrong** [comment]
`ReactFormApi` has been exposed in #868
