### ISSUE TITLE
TypeError on validatorAdapter when passing form schema generic to useForm

### ISSUE THREAD

**Issue by austinm911** [TanStack/form#842]
### Describe the bug

When passing a schema to get typesafety on default values, theres a type error on validatorAdapter. 

`useForm<FormSchema, ReturnType<typeof zodValidator>>` will fix it but seems like a problem if you decide to use a different validation lib down the road and you have these types everywhere. 

And as far as I understand, if you're passing the form as a prop elsewhere to other components, you have to remember to pass the ` ReturnType<typeof zodValidator>` along as a generic to that type definition or else I think there will be type errors. 

```ts
type FormSchema = {
  firstName: string;
  lastName: string;
};

export default function App() {
  const form = useForm<FormSchema>({
    defaultValues: {
      firstName: '',
      lastName: '',
    },
    onSubmit: async ({ value }) => {
      // Do something with form data
      console.log(value)
    },
    // Add a validator to support Zod usage in Form and Field
    validatorAdapter: zodValidator(), // ERROR
  })

```

```
Type '() => { validate({ value }: { value: unknown; }, fn: ZodType<any, ZodTypeDef, any>): ValidationError; validateAsync({ value }: { value: unknown; }, fn: ZodType<any, ZodTypeDef, any>): Promise<...>; }' is not assignable to type 'undefined'.(
```

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-form-s6898n?file=src/index.tsx&preset=node

### Steps to reproduce

see repro

### Expected behavior

should not need to pass the validator along

### How often does this bug happen?

None

### Platform

macos

### TanStack Form adapter

react-form

### TanStack Form version

0.26.1

### TypeScript version

5.5

**Comment by crutchcorn** [comment]
This is impossible to fix via TypeScript, as partial inferencing is not supported. Closing.

**Comment by betoobernal** [comment]
i'm also facing this error.

**Comment by Balastrong** [comment]
> i'm also facing this error. The console in the browser says me: "TypeError: adapter is not a function"

Update `@tanstack/zod-form-adapter` to the latest version (0.29.2 or higher) and try with `useForm<YourFormSchema, ZodValidator>`.
