### ISSUE TITLE
ts error with useField: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by francois-pasquier** [TanStack/form#887]
### Describe the bug

Using useField results in the typescript error in the title.

See this commit: https://github.com/TanStack/form/compare/main...francois-pasquier:form-deep-instantiation-repro:main

### Your minimal, reproducible example

https://github.com/francois-pasquier/form-deep-instantiation-repro

### Steps to reproduce

1. use useField

### Expected behavior

No typescript error

### How often does this bug happen?

Every time

### Platform

in code.

### TanStack Form adapter

None

### TanStack Form version

0.26.4

### TypeScript version

5.5.4

**Comment by Balastrong** [comment]
`useField` is mostly an internal api, what do you need it for?

If you want to access a field's value you can use `useStore` ([more on reactivity in the docs](https://tanstack.com/form/latest/docs/framework/react/guides/basic-concepts#reactivity))

```ts
const firstName = form.useStore((state) => state.values.firstName)
```

**Comment by francois-pasquier** [comment]
Oh, I had no clue useStore could do that.

I was using it for accessing errors, handleBlur, isValiding and my field value for a subcomponent.

I will just switch to using getMeta() and useStore for that then!

Should this issue be closed though?

**Comment by Balastrong** [comment]
Unless there are still cases not covered by `useStore` (happy to talk about those if any!) yeah, we can close this :)
