### ISSUE TITLE
There is no easy or documented way to use `<button type="submit" name="...">`

### ISSUE THREAD

**Issue by chvanam** [TanStack/form#890]
### Discussed in https://github.com/TanStack/form/discussions/886

According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#name) for the `<button>` element, when a `<button type="submit">` has a `name` and optional `value` attribute and triggers a form submission, it also add the `name/value` pair as part of the submitted form data.

Currently, there is no easy or built-in way to access this form data.

**Comment by crutchcorn** [comment]
This feels outside of the prevue of this library. You can still do things like change the `onSubmit` handler to access `FormData` and append it to the form data, but the point of this library is more to handle `input` types and validation. That button doesn't sound like it needs validation anyway.

Closing as I can't think of a usage for this in our library or other libraries that support this API, but do feel free to discuss further if there's something I missed
