### ISSUE TITLE
Image in README mistakenly mentions Svelte support

### ISSUE THREAD

**Issue by mcmxcdev** [TanStack/form#894]
### Describe the bug

I would love it but there is currently no Svelte version, so please remove "Svelte" from the image which can be misleading:

![image](https://github.com/user-attachments/assets/937f0e59-1d50-461f-a285-0131d38ddf4e)

### Your minimal, reproducible example

-

### Steps to reproduce

-

### Expected behavior

-

### How often does this bug happen?

None

### Platform

-

### TanStack Form adapter

None

### TanStack Form version

-

**Comment by Balastrong** [comment]
Nice catch! I'm replacing it now, thank you :)
