### ISSUE TITLE
Form Validation Zod Type Error on Validators

### ISSUE THREAD

**Issue by austinm911** [TanStack/form#916]
### Describe the bug

Noticed this type error appears when validating on form level. Stackblitz isn't previewing for me so not sure if the link will work and you might have to open it locally.

```ts
const formSchema = z.object({
	firstName: z.string().min(3, "First name must be at least 3 characters"),
	lastName: z.string().min(3, "Last name must be at least 3 characters"),
});

type FormSchema = z.infer<typeof formSchema>;

const form = useForm<FormSchema, ZodValidator>({
		defaultValues: {
			firstName: "",
			lastName: "",
		},
		onSubmit: async ({ value }) => {
			// Do something with form data
			console.log(value);
		},
		validators: {
			// Error: Type '({ value }: { value: any; }) => string | undefined' is not assignable to type 'ZodType<any, ZodTypeDef, any>'.
			onChange({ value }) {
				const result = formSchema.safeParse(value)

				return result.success
					? undefined
					: result.error.errors.map((err) => err.message).join(", ");
			},
		},
		// Add a validator to support Zod usage in Form and Field
		validatorAdapter: zodValidator(),
	});
```

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-form-rbhrif?file=src/index.tsx

### Steps to reproduce

run repro

### Expected behavior

no error

### How often does this bug happen?

None

### Platform

macos

### TanStack Form adapter

react-form

### TanStack Form version

0.29.2

**Comment by Balastrong** [comment]
Good news, the error is correct and we can simplify your code to make it work :)


Here you declared that you using a validator (zod) and you made explicit with the type:
```ts
const form = useForm<FormSchema, ZodValidator>({
  ...
  validatorAdapter: zodValidator()
}
```

Which is the same as telling the form "hey, I'm not defining a validator myself, I'm gonna use zod".

However in the onChange function you provided a manual validator, when the form was expecting a zod schema.

If you want to get the best out of the validator, your onChange will be as simple as:
```ts
onChange: formSchema
```

And you can also remove the explicit types from the form definition, they're only needed when creating custom components but as long as you don't need to pass the form instance anywhere, types are inferred automatically
```diff
-const form = useForm<FormSchema, ZodValidator>({
+const form = useForm({
```
