### ISSUE TITLE
zod-form-adapter turns all errors into one comma separated string, meta.errors assumes an array

### ISSUE THREAD

**Issue by Pascalmh** [TanStack/form#942]
### Describe the bug

At the moment the zod-form-adapter's zodValidator `validate` and `validateAsync` functions turn the errors that zod reports into a comma separated string:

```ts
return result.error.issues.map((issue) => issue.message).join(', ')
```

When we want to display the Error(s) to the User the `field.state.meta.errors` field returns an array `ValidationError[]` which now only has one entry (the comma separated string.

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-form-r8vroz?file=src%2Findex.tsx

### Steps to reproduce

1. Open the Stackblitz
2. The Form is already in the Error state (the Input `#` does not match the min-length nor the regex (letters a-Z)
3. Observe: both Error messages are separated by a comma and a space => should only be a comma, see FieldInfo-Function
4. You can also check the Console (you can filter for the string "errors")

### Expected behavior

**As a User** 
I expect `field.state.meta.errors` to be an array (type: `ValidationError[]`) with a length that matches the number of errors that resulted from the zod schema validation

**BUT** 
I'm seeing an array (type: `ValidationError[]`) with the length of `1` no matter how many validation errors occurred.

### How often does this bug happen?

Every time

### Platform

Not platform related

### TanStack Form adapter

react-form

### TanStack Form version

0.32.0

**Comment by Pascalmh** [comment]
I think there is a bug in the definition of the `ValidationError` type 

It is [currently defined](https://github.com/TanStack/form/blob/main/packages/form-core/src/types.ts#L3) as: 
```ts
export type ValidationError = undefined | false | null | string
```

Searching through the codebase [there are places](https://github.com/TanStack/form/blob/main/packages/form-core/src/FieldApi.ts#L860-L861) where `ValidationError | undefined` is specified:

```ts
const validatesPromises: Promise<ValidationError | undefined>[] = []
const linkedPromises: Promise<ValidationError | undefined>[] = []
```

This doesn't make sense as `ValidationError` already includes `undefined` in the union type.

Then there's [this](https://github.com/TanStack/form/blob/main/packages/form-core/src/FieldApi.ts#L353C3-L353C28):

```
/**
   * An array of errors related to the field value.
   */
errors: ValidationError[]
```

where errors is an array of ValidationError - where the items of the array could be of type `undefined | false | null | string` so working with the errors requires an additional falsy check.

### How to fix it?

My guess is that the ValidationError should be `Array<string> | undefined | false | null`

### Related Issues
- 
- This discussion seams related as well: https://github.com/TanStack/form/discussions/946

**Comment by mimamuh** [comment]
I have the same issue and wonder why this issue is not commented/flagged yet. Is this a bug or a feature? Personally, I would prefer not having the errors be joined, because I can do so myself. But maybe there is a kind of a custom formatter option or something like that?

**Comment by adhithiya05** [comment]
I have the same issue too.

**Comment by mimamuh** [comment]
@adhithiya05 You can work around this by using the `transformErrors` option of the `zodValidator` like so; sadly it doesn't allow returning an array currently:
```javascript
validatorAdapter: zodValidator({
    transformErrors: (errors) => {
        return errors.map(error => error.message).join('#!#'); 
    }
}),
``` 
And somewhere in your form / component you simply split the error again:
```javascript
errors[0].split('#!#');
```

**Comment by Balastrong** [comment]
Replacing `string` with `string[]` in `ValidationError` would be a massive breaking change, forcing all validators to return an array instead of a string all the time. I'm not sure we should go that way.

A tradeoff could be accepting both `string | string[]`. This would leave all existing validators untouched but still introduce a tiny breaking change since `meta.errorMap.onChange` & co would no longer be `string` but `string | string[]` and the user has to handle that explicitly all the time.

That might be an edge case though as in all examples we're usually recommending to display all errors in `meta.errors` that is already an array (it's the aggregated of all the errors from all validators). We can simply flatMap the errors internally to avoid exposing `string[][]` errors, not a big deal.


With that said, I see the benefit of having arrays and I'm in for exploring the change :)
