### ISSUE TITLE
validatorAdapter doesn't accept useForm's generic type

### ISSUE THREAD

**Issue by mmospanenko** [TanStack/form#950]
### Describe the bug

When I add type to useForm (useForm<MyType>), property validatorAdapter shows wrong typing. Without generic validatorAdapter works correctly but I lose form typing.

```ts
  const form = useForm<MyType>({
    onSubmit: ({ value }) => submit(value),
    validatorAdapter: valibotValidator(),
  });
```

```
Type 'Validator<unknown, GenericSchema<unknown, unknown, BaseIssue<unknown>> | GenericSchemaAsync<unknown, unknown, BaseIssue<unknown>>>' is not assignable to type 'undefined'.
```

![Image](https://github.com/user-attachments/assets/39956bf4-826f-45ec-91ed-bd28ea98d9f9)

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-qinj2o?file=src%2FApp.tsx

### Steps to reproduce

1. try to use useForm with generic and valibotValidator
2. see a TS error

### Expected behavior

validatorAdapter should get types from useForm

### How often does this bug happen?

Every time

### Platform

TS 5.5.4

### TanStack Form adapter

None

### TanStack Form version

0.32.0

### TypeScript version

5.5.4

### Additional context

@tanstack/valibot-form-adapter 0.32.0
valibot 0.42.0

**Comment by Balastrong** [comment]
You can either:

A) Get form types by providing a `defaultValues` object, so you won't need to be explicit with generics in `useForm({ ... })` and you still have typesafety (see [simple](https://tanstack.com/form/latest/docs/framework/react/examples/simple) demo)
or
B) If you specify the form type with the generic, you must also feed the right validator type. In your case:
```ts
import { ValibotValidator, valibotValidator } from '@tanstack/valibot-form-adapter';

...

useForm<MyType, ValibotValidator>({ ... })
```

Option A is recommended but B also works :)

**Comment by mmospanenko** [comment]
thank you, I have to read the documentation more carefully :)

**Comment by paschaldev** [comment]
![Image](https://github.com/user-attachments/assets/6cfd7f63-cb0c-4097-ac6f-af0b72413541)
This doesn't work with Zod or I'm missing something

**Comment by Balastrong** [comment]
Might be a version mismatch? Can you check if both `@tanstack/react-form` and `@tanstack/zod-form-adapter` are at the same version? Latest would be 0.33

If it still throws an error could you please replicate it on a stackblitz and create a new issue? You can fork the [zod example](https://tanstack.com/form/latest/docs/framework/react/examples/zod) as a starting point.

This seems to be working fine in the example:
```ts
  const form = useForm<{ firstName: string; lastName: string }, ZodValidator>({
    defaultValues: {
      firstName: '',
      lastName: '',
    },
    validatorAdapter: zodValidator(),
  });
```
